server:
  port: 8080
  compression: # embedded tomcat 기동 시에 사용되는 설정. tomcat server 에서 실행할 경우는 server.xml 에 설정.
    min-response-size: 1
    enabled: true

spring:
  application:
    name: children-meal
  profiles:
    active: local
mvc:
  throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    static-locations: ["/static/"]

thymeleaf:
  prefix: "classpath:resources/templates/"
  suffix: ".html"

mybatis:
  path:
    config: classpath:/mybatis-config.xml
    mapper: classpath:/mapper/*.xml
    type-aliases: meal

---

app:
  datasource:
    master:
      driver-class-bame: com.mysql.jdbc.driver
      url: jdbc:mysql://127.0.0.1:3306/children_meal?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8_bin&characterSetResults=utf8&serverTimezone=Asia/Seoul&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnectForPools=true
      username: root
      password: s82231334s!
      validation-query: select 1
      test-on-borrow: true
      validation-interval: 10000
      default-auto-commit: true
      pool-prepared-statements: true
      initial-size: 1
      max-active: 3
      max-idle: 3
      min-idle: 3
      max-wait: 3000